import sys, res
import sys, res
import sys, res
import sys, res
import sys, res
import sys, res
import sys, res
import sys, res
import sys, res
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddWorkoutV2.ui'
#
# Created by: PyQt5 UI code generator 5.15.20
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QScrollArea, QWidget, QGridLayout, QPushButton, QComboBox, QLineEdit
import mysql.connector



class ui_AddWorkout(object):
        def setupUi(self, MainWindow, UserID):
                MainWindow.setObjectName("MainWindow")
                MainWindow.resize(897, 494)
                MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
                self.MainWindowWidget = QtWidgets.QWidget(MainWindow)
                self.MainWindowWidget.setStyleSheet("layoutLeftMargin")
                self.MainWindowWidget.setObjectName("MainWindowWidget")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainWindowWidget)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.splitter = QtWidgets.QSplitter(self.MainWindowWidget)
                self.splitter.setOrientation(QtCore.Qt.Horizontal)
                self.splitter.setObjectName("splitter")
                self.LeftMenuWidget = QtWidgets.QWidget(self.splitter)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.LeftMenuWidget.sizePolicy().hasHeightForWidth())
                self.LeftMenuWidget.setSizePolicy(sizePolicy)
                self.LeftMenuWidget.setMaximumSize(QtCore.QSize(310, 16777215))
                self.LeftMenuWidget.setStyleSheet("QWidget {\n"
        "    background-color: #F3F3F3; \n"
        "}")
                self.LeftMenuWidget.setObjectName("LeftMenuWidget")
                self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.LeftMenuWidget)
                self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
                self.verticalLayout_9.setObjectName("verticalLayout_9")
                self.NameWidget = QtWidgets.QWidget(self.LeftMenuWidget)
                self.NameWidget.setMaximumSize(QtCore.QSize(16777215, 75))
                self.NameWidget.setObjectName("NameWidget")
                self.verticalLayout = QtWidgets.QVBoxLayout(self.NameWidget)
                self.verticalLayout.setObjectName("verticalLayout")
                self.NameLabel = QtWidgets.QLabel(self.NameWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.NameLabel.sizePolicy().hasHeightForWidth())
                self.NameLabel.setSizePolicy(sizePolicy)
                self.NameLabel.setMaximumSize(QtCore.QSize(16777215, 75))
                self.NameLabel.setObjectName("NameLabel")
                self.verticalLayout.addWidget(self.NameLabel)
                self.verticalLayout_9.addWidget(self.NameWidget)
                self.SearchWidget = QtWidgets.QWidget(self.LeftMenuWidget)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.SearchWidget.sizePolicy().hasHeightForWidth())
                self.SearchWidget.setSizePolicy(sizePolicy)
                self.SearchWidget.setMaximumSize(QtCore.QSize(16777215, 75))
                self.SearchWidget.setObjectName("SearchWidget")
                self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.SearchWidget)
                self.verticalLayout_7.setObjectName("verticalLayout_7")
                self.SearchBar = QtWidgets.QLineEdit(self.SearchWidget)
                self.SearchBar.setMaximumSize(QtCore.QSize(16777215, 50))
                self.SearchBar.setStyleSheet("QLineEdit {\n"
        "\n"
        "    padding-right: 20px; /* Adjust padding so text does not overlap the icon */\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-top: 2px;\n"
        "    padding-bottom: 7px;\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.SearchBar.setText("")
                self.SearchBar.setObjectName("SearchBar")
                self.verticalLayout_7.addWidget(self.SearchBar)
                self.verticalLayout_9.addWidget(self.SearchWidget)
                self.UpperListWidget = QtWidgets.QWidget(self.LeftMenuWidget)
                self.UpperListWidget.setMaximumSize(QtCore.QSize(16777215, 200))
                self.UpperListWidget.setObjectName("UpperListWidget")
                self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.UpperListWidget)
                self.verticalLayout_3.setObjectName("verticalLayout_3")
                self.GoalsButton = QtWidgets.QPushButton(self.UpperListWidget)
                self.GoalsButton.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 10px;\n"
        "")
                self.GoalsButton.setObjectName("GoalsButton")
                self.verticalLayout_3.addWidget(self.GoalsButton)
                self.EventsButton = QtWidgets.QPushButton(self.UpperListWidget)
                self.EventsButton.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 10px;\n"
        "")
                self.EventsButton.setObjectName("EventsButton")
                self.verticalLayout_3.addWidget(self.EventsButton)
                self.WorkoutsButton = QtWidgets.QPushButton(self.UpperListWidget)
                self.WorkoutsButton.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 10px;\n"
        "")
                self.WorkoutsButton.setObjectName("WorkoutsButton")
                self.verticalLayout_3.addWidget(self.WorkoutsButton)
                self.StatsButton = QtWidgets.QPushButton(self.UpperListWidget)
                self.StatsButton.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 10px;\n"
        "")
                self.StatsButton.setObjectName("StatsButton")
                self.verticalLayout_3.addWidget(self.StatsButton)
                self.ProgressButton = QtWidgets.QPushButton(self.UpperListWidget)
                self.ProgressButton.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 10px;\n"
        "")
                self.ProgressButton.setObjectName("ProgressButton")
                self.verticalLayout_3.addWidget(self.ProgressButton)
                self.line = QtWidgets.QFrame(self.UpperListWidget)
                self.line.setStyleSheet("color: black; \n"
        "")
                self.line.setFrameShape(QtWidgets.QFrame.HLine)
                self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
                self.line.setObjectName("line")
                self.verticalLayout_3.addWidget(self.line)
                self.verticalLayout_9.addWidget(self.UpperListWidget)
                self.LowerListWidget = QtWidgets.QWidget(self.LeftMenuWidget)
                self.LowerListWidget.setMaximumSize(QtCore.QSize(16777215, 150))
                self.LowerListWidget.setStyleSheet("")
                self.LowerListWidget.setObjectName("LowerListWidget")
                self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.LowerListWidget)
                self.verticalLayout_8.setObjectName("verticalLayout_8")
                self.SettingsButton = QtWidgets.QPushButton(self.LowerListWidget)
                self.SettingsButton.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 10px;\n"
        "")
                self.SettingsButton.setObjectName("SettingsButton")
                self.verticalLayout_8.addWidget(self.SettingsButton)
                self.HelpButton = QtWidgets.QPushButton(self.LowerListWidget)
                self.HelpButton.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 10px;\n"
        "")
                self.HelpButton.setObjectName("HelpButton")
                self.verticalLayout_8.addWidget(self.HelpButton)
                self.LogOutButton = QtWidgets.QPushButton(self.LowerListWidget)
                self.LogOutButton.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 10px;\n"
        "")
                self.LogOutButton.setObjectName("LogOutButton")
                self.verticalLayout_8.addWidget(self.LogOutButton)
                self.verticalLayout_9.addWidget(self.LowerListWidget)
                self.MainStackedWidget = QtWidgets.QStackedWidget(self.splitter)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.MainStackedWidget.sizePolicy().hasHeightForWidth())
                self.MainStackedWidget.setSizePolicy(sizePolicy)
                self.MainStackedWidget.setStyleSheet("QWidget {\n"
        "    background-color: #FFFFFF; \n"
        "}")


                self.MainStackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
                self.MainStackedWidget.setLineWidth(0)
                self.MainStackedWidget.setObjectName("MainStackedWidget")
                self.page1 = QtWidgets.QWidget()
                self.page1.setObjectName("page1")
                self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page1)
                self.verticalLayout_10.setObjectName("verticalLayout_10")
                self.DashboardWidget = QtWidgets.QWidget(self.page1)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.DashboardWidget.sizePolicy().hasHeightForWidth())
                self.DashboardWidget.setSizePolicy(sizePolicy)
                self.DashboardWidget.setObjectName("DashboardWidget")
                self.gridLayout = QtWidgets.QGridLayout(self.DashboardWidget)
                self.gridLayout.setObjectName("gridLayout")
                self.DistanceLabel_5 = QtWidgets.QLabel(self.DashboardWidget)
                self.DistanceLabel_5.setMaximumSize(QtCore.QSize(16777215, 40))
                font = QtGui.QFont()
                font.setPointSize(8)
                self.DistanceLabel_5.setFont(font)
                self.DistanceLabel_5.setStyleSheet("color: black; \n"
        "")
                self.DistanceLabel_5.setObjectName("DistanceLabel_5")
                self.gridLayout.addWidget(self.DistanceLabel_5, 4, 0, 1, 2)
                self.DurationLabel_5 = QtWidgets.QLabel(self.DashboardWidget)
                self.DurationLabel_5.setMaximumSize(QtCore.QSize(16777215, 40))
                font = QtGui.QFont()
                font.setPointSize(8)
                self.DurationLabel_5.setFont(font)
                self.DurationLabel_5.setStyleSheet("color: black; \n"
        "")
                self.DurationLabel_5.setObjectName("DurationLabel_5")
                self.gridLayout.addWidget(self.DurationLabel_5, 4, 2, 1, 1)
                self.GWorkoutsAmount_5 = QtWidgets.QLabel(self.DashboardWidget)
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.GWorkoutsAmount_5.setFont(font)
                self.GWorkoutsAmount_5.setStyleSheet("color: black; \n"
        "")
                self.GWorkoutsAmount_5.setObjectName("GWorkoutsAmount_5")
                self.gridLayout.addWidget(self.GWorkoutsAmount_5, 3, 7, 1, 1)
                self.GWorkoutsLabel_5 = QtWidgets.QLabel(self.DashboardWidget)
                self.GWorkoutsLabel_5.setMaximumSize(QtCore.QSize(16777215, 40))
                font = QtGui.QFont()
                font.setPointSize(8)
                self.GWorkoutsLabel_5.setFont(font)
                self.GWorkoutsLabel_5.setStyleSheet("color: black; \n"
        "")
                self.GWorkoutsLabel_5.setObjectName("GWorkoutsLabel_5")
                self.gridLayout.addWidget(self.GWorkoutsLabel_5, 4, 6, 1, 1)
                self.RacesLabel_5 = QtWidgets.QLabel(self.DashboardWidget)
                self.RacesLabel_5.setMaximumSize(QtCore.QSize(16777215, 40))
                font = QtGui.QFont()
                font.setPointSize(8)
                self.RacesLabel_5.setFont(font)
                self.RacesLabel_5.setStyleSheet("color: black; \n"
        "")
                self.RacesLabel_5.setObjectName("RacesLabel_5")
                self.gridLayout.addWidget(self.RacesLabel_5, 4, 7, 1, 1)
                self.GymFilterButton_5 = QtWidgets.QPushButton(self.DashboardWidget)
                self.GymFilterButton_5.setMaximumSize(QtCore.QSize(40, 16777215))
                self.GymFilterButton_5.setStyleSheet("color: black; \n"
        "\n"
        "background: transparent;\n"
        "text-align: center; /* Align the text inside the QPushButton to the left */\n"
        "border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "border: 1px solid rgba(105, 118, 132, 255);\n"
        "\n"
        "\n"
        "")
                self.GymFilterButton_5.setObjectName("GymFilterButton_5")
                self.gridLayout.addWidget(self.GymFilterButton_5, 2, 2, 1, 1)
                self.RacesAmount_5 = QtWidgets.QLabel(self.DashboardWidget)
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.RacesAmount_5.setFont(font)
                self.RacesAmount_5.setStyleSheet("color: black; \n"
        "")
                self.RacesAmount_5.setObjectName("RacesAmount_5")
                self.gridLayout.addWidget(self.RacesAmount_5, 3, 6, 1, 1)
                self.TWorkoutsAmount_5 = QtWidgets.QLabel(self.DashboardWidget)
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.TWorkoutsAmount_5.setFont(font)
                self.TWorkoutsAmount_5.setStyleSheet("color: black; \n"
        "")
                self.TWorkoutsAmount_5.setObjectName("TWorkoutsAmount_5")
                self.gridLayout.addWidget(self.TWorkoutsAmount_5, 3, 4, 1, 1)
                self.AllFilterButton_5 = QtWidgets.QPushButton(self.DashboardWidget)
                self.AllFilterButton_5.setMaximumSize(QtCore.QSize(50, 16777215))
                self.AllFilterButton_5.setStyleSheet("color: black; \n"
        "\n"
        "background: transparent;\n"
        "text-align: center; /* Align the text inside the QPushButton to the left */\n"
        "border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "border: 1px solid rgba(105, 118, 132, 255);\n"
        "\n"
        "\n"
        "")
                self.AllFilterButton_5.setObjectName("AllFilterButton_5")
                self.gridLayout.addWidget(self.AllFilterButton_5, 2, 0, 1, 1)
                self.DistanceAmount_5 = QtWidgets.QLabel(self.DashboardWidget)
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.DistanceAmount_5.setFont(font)
                self.DistanceAmount_5.setStyleSheet("color: black; \n"
        "")
                self.DistanceAmount_5.setObjectName("DistanceAmount_5")
                self.gridLayout.addWidget(self.DistanceAmount_5, 3, 0, 1, 1)
                self.TrainingFilterButton_5 = QtWidgets.QPushButton(self.DashboardWidget)
                self.TrainingFilterButton_5.setMaximumSize(QtCore.QSize(70, 16777215))
                self.TrainingFilterButton_5.setStyleSheet("color: black; \n"
        "\n"
        "background: transparent;\n"
        "text-align: center; /* Align the text inside the QPushButton to the left */\n"
        "border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "border: 1px solid rgba(105, 118, 132, 255);\n"
        "\n"
        "\n"
        "")
                self.TrainingFilterButton_5.setObjectName("TrainingFilterButton_5")
                self.gridLayout.addWidget(self.TrainingFilterButton_5, 2, 1, 1, 1)
                self.DurationAmount_5 = QtWidgets.QLabel(self.DashboardWidget)
                font = QtGui.QFont()
                font.setPointSize(14)
                font.setBold(True)
                font.setWeight(75)
                self.DurationAmount_5.setFont(font)
                self.DurationAmount_5.setStyleSheet("color: black; \n"
        "")
                self.DurationAmount_5.setObjectName("DurationAmount_5")
                self.gridLayout.addWidget(self.DurationAmount_5, 3, 2, 1, 2)
                self.ActivityLabel_5 = QtWidgets.QLabel(self.DashboardWidget)
                self.ActivityLabel_5.setMaximumSize(QtCore.QSize(16777215, 20))
                font = QtGui.QFont()
                font.setFamily("MS Shell Dlg 2")
                font.setPointSize(6)
                font.setBold(True)
                font.setWeight(75)
                self.ActivityLabel_5.setFont(font)
                self.ActivityLabel_5.setStyleSheet("color: black; \n"
        "")
                self.ActivityLabel_5.setObjectName("ActivityLabel_5")
                self.gridLayout.addWidget(self.ActivityLabel_5, 1, 0, 1, 1)
                self.RaceFilterButton_5 = QtWidgets.QPushButton(self.DashboardWidget)
                self.RaceFilterButton_5.setStyleSheet("color: black; \n"
        "\n"
        "background: transparent;\n"
        "text-align: center; /* Align the text inside the QPushButton to the left */\n"
        "border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "border: 1px solid rgba(105, 118, 132, 255);\n"
        "\n"
        "\n"
        "")
                self.RaceFilterButton_5.setObjectName("RaceFilterButton_5")
                self.gridLayout.addWidget(self.RaceFilterButton_5, 2, 3, 1, 1)
                self.TWorkoutsLabel_5 = QtWidgets.QLabel(self.DashboardWidget)
                self.TWorkoutsLabel_5.setMaximumSize(QtCore.QSize(16777215, 40))
                font = QtGui.QFont()
                font.setPointSize(8)
                self.TWorkoutsLabel_5.setFont(font)
                self.TWorkoutsLabel_5.setStyleSheet("color: black; \n"
        "")
                self.TWorkoutsLabel_5.setObjectName("TWorkoutsLabel_5")
                self.gridLayout.addWidget(self.TWorkoutsLabel_5, 4, 4, 1, 2)
                self.verticalLayout_10.addWidget(self.DashboardWidget)
                self.WorkoutLogWidget = QtWidgets.QWidget(self.page1)
                sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
                sizePolicy.setHorizontalStretch(0)
                sizePolicy.setVerticalStretch(0)
                sizePolicy.setHeightForWidth(self.WorkoutLogWidget.sizePolicy().hasHeightForWidth())
                self.WorkoutLogWidget.setSizePolicy(sizePolicy)
                self.WorkoutLogWidget.setStyleSheet("QWidget {\n"
        "border-radius: 400px;\n"
        "    background-color: #F3F3F3; \n"
        "}")
                self.WorkoutLogWidget.setObjectName("WorkoutLogWidget")
                self.gridLayout_2 = QtWidgets.QGridLayout(self.WorkoutLogWidget)
                self.gridLayout_2.setObjectName("gridLayout_2")
                self.DateLabelDash_5 = QtWidgets.QLabel(self.WorkoutLogWidget)
                font = QtGui.QFont()
                font.setPointSize(8)
                self.DateLabelDash_5.setFont(font)
                self.DateLabelDash_5.setStyleSheet("color: black; \n"
        "")
                self.DateLabelDash_5.setObjectName("DateLabelDash_5")
                self.gridLayout_2.addWidget(self.DateLabelDash_5, 0, 0, 1, 1)
                self.ActivityLabelDash_5 = QtWidgets.QLabel(self.WorkoutLogWidget)
                font = QtGui.QFont()
                font.setPointSize(8)
                self.ActivityLabelDash_5.setFont(font)
                self.ActivityLabelDash_5.setStyleSheet("color: black; \n"
        "")
                self.ActivityLabelDash_5.setObjectName("ActivityLabelDash_5")
                self.gridLayout_2.addWidget(self.ActivityLabelDash_5, 0, 1, 1, 1)
                self.DistancesLabelDash_5 = QtWidgets.QLabel(self.WorkoutLogWidget)
                font = QtGui.QFont()
                font.setPointSize(8)
                self.DistancesLabelDash_5.setFont(font)
                self.DistancesLabelDash_5.setStyleSheet("color: black; \n"
        "")
                self.DistancesLabelDash_5.setObjectName("DistancesLabelDash_5")
                self.gridLayout_2.addWidget(self.DistancesLabelDash_5, 0, 2, 1, 1)
                self.FocusLabelDash_5 = QtWidgets.QLabel(self.WorkoutLogWidget)
                font = QtGui.QFont()
                font.setPointSize(8)
                self.FocusLabelDash_5.setFont(font)
                self.FocusLabelDash_5.setStyleSheet("color: black; \n"
        "")
                self.FocusLabelDash_5.setObjectName("FocusLabelDash_5")
                self.gridLayout_2.addWidget(self.FocusLabelDash_5, 0, 3, 1, 1)
                self.stackedWidget_6 = QtWidgets.QStackedWidget(self.WorkoutLogWidget)
                self.stackedWidget_6.setStyleSheet("QWidget {\n"
        "border-radius: 400px;\n"
        "    background-color: #000; \n"
        "}")
                self.stackedWidget_6.setObjectName("stackedWidget_6")
                self.page_26 = QtWidgets.QWidget()
                self.page_26.setObjectName("page_26")
                self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.page_26)
                self.verticalLayout_11.setObjectName("verticalLayout_11")
                self.AddWorkoutButtonWidget_5 = QtWidgets.QPushButton(self.page_26)
                self.AddWorkoutButtonWidget_5.setMaximumSize(QtCore.QSize(16777215, 75))
                font = QtGui.QFont()
                font.setFamily("Symbol")
                font.setPointSize(32)
                self.AddWorkoutButtonWidget_5.setFont(font)
                self.AddWorkoutButtonWidget_5.setStyleSheet("color: black; \n"
        "")
                self.AddWorkoutButtonWidget_5.setObjectName("AddWorkoutButtonWidget_5")
                self.verticalLayout_11.addWidget(self.AddWorkoutButtonWidget_5)
                self.WorkoutsAmountDefaultLabel_5 = QtWidgets.QLabel(self.page_26)
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.WorkoutsAmountDefaultLabel_5.setFont(font)
                self.WorkoutsAmountDefaultLabel_5.setStyleSheet("color: black; \n"
        "")
                self.WorkoutsAmountDefaultLabel_5.setObjectName("WorkoutsAmountDefaultLabel_5")
                self.verticalLayout_11.addWidget(self.WorkoutsAmountDefaultLabel_5)
                self.stackedWidget_6.addWidget(self.page_26)
                self.page_27 = QtWidgets.QWidget()
                self.page_27.setObjectName("page_27")
                self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.page_27)
                self.verticalLayout_12.setObjectName("verticalLayout_12")
                self.stackedWidget_6.addWidget(self.page_27)
                self.gridLayout_2.addWidget(self.stackedWidget_6, 1, 0, 1, 4)
                self.verticalLayout_10.addWidget(self.WorkoutLogWidget)
                self.MainStackedWidget.addWidget(self.page1)
                self.page = QtWidgets.QWidget()
                self.page.setObjectName("page")
                self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page)
                self.verticalLayout_6.setObjectName("verticalLayout_6")
                self.widget = QtWidgets.QWidget(self.page)
                self.widget.setObjectName("widget")
                self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
                self.verticalLayout_2.setObjectName("verticalLayout_2")
                self.widget_2 = QtWidgets.QWidget(self.widget)
                self.widget_2.setObjectName("widget_2")
                self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
                self.verticalLayout_4.setObjectName("verticalLayout_4")
                self.label_2 = QtWidgets.QLabel(self.widget_2)
                self.label_2.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_2.setObjectName("label_2")
                self.verticalLayout_4.addWidget(self.label_2)
                self.lineEdit = QtWidgets.QLineEdit(self.widget_2)
                self.lineEdit.setMaximumSize(QtCore.QSize(400, 25))
                self.lineEdit.setStyleSheet("QLineEdit {\n"
        "\n"
        "    padding-right: 20px; /* Adjust padding so text does not overlap the icon */\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-top: 2px;\n"
        "    padding-bottom: 7px;\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit.setText("")
                self.lineEdit.setObjectName("lineEdit")
                self.verticalLayout_4.addWidget(self.lineEdit)
                self.label_3 = QtWidgets.QLabel(self.widget_2)
                self.label_3.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_3.setObjectName("label_3")
                self.verticalLayout_4.addWidget(self.label_3)
                self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_2)
                self.lineEdit_2.setMaximumSize(QtCore.QSize(200, 25))
                self.lineEdit_2.setStyleSheet("QLineEdit {\n"
        "\n"
        "    padding-right: 20px; /* Adjust padding so text does not overlap the icon */\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-top: 2px;\n"
        "    padding-bottom: 7px;\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit_2.setText("")
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.verticalLayout_4.addWidget(self.lineEdit_2)
                self.label_4 = QtWidgets.QLabel(self.widget_2)
                self.label_4.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_4.setObjectName("label_4")
                self.verticalLayout_4.addWidget(self.label_4)
                self.lineEdit_3 = QtWidgets.QLineEdit(self.widget_2)
                self.lineEdit_3.setMaximumSize(QtCore.QSize(200, 25))
                self.lineEdit_3.setStyleSheet("QLineEdit {\n"
        "\n"
        "    padding-right: 20px; /* Adjust padding so text does not overlap the icon */\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-top: 2px;\n"
        "    padding-bottom: 7px;\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit_3.setText("")
                self.lineEdit_3.setObjectName("lineEdit_3")
                self.verticalLayout_4.addWidget(self.lineEdit_3)
                self.widget_3 = QtWidgets.QWidget(self.widget_2)
                self.widget_3.setObjectName("widget_3")
                self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
                self.verticalLayout_5.setObjectName("verticalLayout_5")
                self.label = QtWidgets.QLabel(self.widget_3)
                self.label.setObjectName("label")
                self.verticalLayout_5.addWidget(self.label)
                self.comboBox = QtWidgets.QComboBox(self.widget_3)
                self.comboBox.setMaximumSize(QtCore.QSize(200, 30))
                self.comboBox.setObjectName("comboBox")
                self.comboBox.addItem("")
                self.comboBox.setItemText(0, "")
                self.comboBox.addItem("")
                self.comboBox.addItem("")
                self.comboBox.addItem("")
                self.verticalLayout_5.addWidget(self.comboBox)
                self.verticalLayout_4.addWidget(self.widget_3)
                self.verticalLayout_2.addWidget(self.widget_2)
                self.verticalLayout_6.addWidget(self.widget)
                self.stackedWidget = QtWidgets.QStackedWidget(self.page)
                self.stackedWidget.setObjectName("stackedWidget")
                
                
                self.page_2 = QtWidgets.QWidget()
                self.page_2.setObjectName("page_2")
                self.stackedWidget.addWidget(self.page_2)
                self.page_3 = QtWidgets.QWidget()
                self.page_3.setObjectName("page_3")
                self.gridLayout_3 = QtWidgets.QGridLayout(self.page_3)
                self.gridLayout_3.setObjectName("gridLayout_3")
                self.widget_5 = QtWidgets.QWidget(self.page_3)
                self.widget_5.setObjectName("widget_5")
                self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
                self.horizontalLayout_2.setObjectName("horizontalLayout_2")
                self.pushButton = QtWidgets.QPushButton(self.widget_5)
                self.pushButton.setObjectName("pushButton")
                self.horizontalLayout_2.addWidget(self.pushButton)
                self.pushButton_2 = QtWidgets.QPushButton(self.widget_5)
                self.pushButton_2.setObjectName("pushButton_2")
                self.horizontalLayout_2.addWidget(self.pushButton_2)
                self.gridLayout_3.addWidget(self.widget_5, 1, 0, 1, 1)
                self.scrollArea = QtWidgets.QScrollArea(self.page_3)
                self.scrollArea.setWidgetResizable(True)
                self.scrollArea.setObjectName("scrollArea")
                self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
                self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 607, 106))
                self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
                self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
                self.verticalLayout_13.setObjectName("verticalLayout_13")
                self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
                self.widget_4.setStyleSheet(" ")
                self.widget_4.setObjectName("widget_4")
                self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_4)
                self.gridLayout_4.setObjectName("gridLayout_4")
                self.label_5 = QtWidgets.QLabel(self.widget_4)
                self.label_5.setMaximumSize(QtCore.QSize(16777215, 20))
                self.label_5.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_5.setObjectName("label_5")
                self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
                self.label_6 = QtWidgets.QLabel(self.widget_4)
                self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
                self.label_6.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_6.setObjectName("label_6")
                self.gridLayout_4.addWidget(self.label_6, 0, 1, 1, 1)
                self.lineEdit_4 = QtWidgets.QLineEdit(self.widget_4)
                self.lineEdit_4.setObjectName("lineEdit_4")
                self.gridLayout_4.addWidget(self.lineEdit_4, 1, 0, 1, 1)
                self.lineEdit_5 = QtWidgets.QLineEdit(self.widget_4)
                self.lineEdit_5.setObjectName("lineEdit_5")
                self.gridLayout_4.addWidget(self.lineEdit_5, 1, 1, 1, 1)
                self.verticalLayout_13.addWidget(self.widget_4)
                self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
                self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
                self.stackedWidget.addWidget(self.page_3)
                self.page_4 = QtWidgets.QWidget()
                self.page_4.setObjectName("page_4")
                self.gridLayout_5 = QtWidgets.QGridLayout(self.page_4)
                self.gridLayout_5.setObjectName("gridLayout_5")
                self.scrollArea_2 = QtWidgets.QScrollArea(self.page_4)
                self.scrollArea_2.setWidgetResizable(True)
                self.scrollArea_2.setObjectName("scrollArea_2")
                self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
                self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 607, 106))
                self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
                self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_3)
                self.horizontalLayout_5.setObjectName("horizontalLayout_5")
                self.widget_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents_3)
                self.widget_6.setStyleSheet("")
                self.widget_6.setObjectName("widget_6")
                self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_6)
                self.gridLayout_6.setObjectName("gridLayout_6")
                self.label_7 = QtWidgets.QLabel(self.widget_6)
                self.label_7.setMaximumSize(QtCore.QSize(16777215, 20))
                self.label_7.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_7.setObjectName("label_7")
                self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
                self.label_8 = QtWidgets.QLabel(self.widget_6)
                self.label_8.setMaximumSize(QtCore.QSize(16777215, 20))
                self.label_8.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_8.setObjectName("label_8")
                self.gridLayout_6.addWidget(self.label_8, 0, 1, 1, 1)
                self.label_9 = QtWidgets.QLabel(self.widget_6)
                self.label_9.setMaximumSize(QtCore.QSize(16777215, 20))
                self.label_9.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_9.setObjectName("label_9")
                self.gridLayout_6.addWidget(self.label_9, 0, 2, 1, 1)
                self.label_10 = QtWidgets.QLabel(self.widget_6)
                self.label_10.setMaximumSize(QtCore.QSize(16777215, 20))
                self.label_10.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_10.setObjectName("label_10")
                self.gridLayout_6.addWidget(self.label_10, 0, 3, 1, 1)
                self.label_11 = QtWidgets.QLabel(self.widget_6)
                self.label_11.setMaximumSize(QtCore.QSize(16777215, 20))
                self.label_11.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_11.setObjectName("label_11")
                self.gridLayout_6.addWidget(self.label_11, 0, 4, 1, 1)
                self.lineEdit_6 = QtWidgets.QLineEdit(self.widget_6)
                self.lineEdit_6.setStyleSheet("QLineEdit {\n"
        "\n"
        "    padding-right: 20px; /* Adjust padding so text does not overlap the icon */\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit_6.setObjectName("lineEdit_6")
                self.gridLayout_6.addWidget(self.lineEdit_6, 1, 0, 1, 1)
                self.lineEdit_7 = QtWidgets.QLineEdit(self.widget_6)
                self.lineEdit_7.setStyleSheet("QLineEdit {\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit_7.setText("")
                self.lineEdit_7.setObjectName("lineEdit_7")
                self.gridLayout_6.addWidget(self.lineEdit_7, 1, 1, 1, 1)
                self.lineEdit_8 = QtWidgets.QLineEdit(self.widget_6)
                self.lineEdit_8.setStyleSheet("QLineEdit {\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit_8.setText("")
                self.lineEdit_8.setObjectName("lineEdit_8")
                self.gridLayout_6.addWidget(self.lineEdit_8, 1, 2, 1, 1)
                self.lineEdit_9 = QtWidgets.QLineEdit(self.widget_6)
                self.lineEdit_9.setStyleSheet("QLineEdit {\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit_9.setText("")
                self.lineEdit_9.setObjectName("lineEdit_9")
                self.gridLayout_6.addWidget(self.lineEdit_9, 1, 3, 1, 1)
                self.lineEdit_10 = QtWidgets.QLineEdit(self.widget_6)
                self.lineEdit_10.setStyleSheet("QLineEdit {\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit_10.setText("")
                self.lineEdit_10.setObjectName("lineEdit_10")
                self.gridLayout_6.addWidget(self.lineEdit_10, 1, 4, 1, 1)
                self.horizontalLayout_5.addWidget(self.widget_6)
                self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
                self.gridLayout_5.addWidget(self.scrollArea_2, 0, 0, 1, 1)
                self.widget_7 = QtWidgets.QWidget(self.page_4)
                self.widget_7.setObjectName("widget_7")
                self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_7)
                self.horizontalLayout_4.setObjectName("horizontalLayout_4")
                self.pushButton_5 = QtWidgets.QPushButton(self.widget_7)
                self.pushButton_5.setObjectName("pushButton_5")
                self.horizontalLayout_4.addWidget(self.pushButton_5)
                self.pushButton_6 = QtWidgets.QPushButton(self.widget_7)
                self.pushButton_6.setObjectName("pushButton_6")
                self.horizontalLayout_4.addWidget(self.pushButton_6)
                self.gridLayout_5.addWidget(self.widget_7, 1, 0, 1, 1)
                self.stackedWidget.addWidget(self.page_4)
                self.page_5 = QtWidgets.QWidget()
                self.page_5.setObjectName("page_5")
                self.gridLayout_8 = QtWidgets.QGridLayout(self.page_5)
                self.gridLayout_8.setObjectName("gridLayout_8")
                self.scrollArea_3 = QtWidgets.QScrollArea(self.page_5)
                self.scrollArea_3.setWidgetResizable(True)
                self.scrollArea_3.setObjectName("scrollArea_3")
                self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
                self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 607, 106))
                self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
                self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_4)
                self.horizontalLayout_6.setObjectName("horizontalLayout_6")
                self.widget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents_4)
                self.widget_8.setStyleSheet("")
                self.widget_8.setObjectName("widget_8")
                self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_8)
                self.gridLayout_7.setObjectName("gridLayout_7")
                self.label_15 = QtWidgets.QLabel(self.widget_8)
                self.label_15.setMaximumSize(QtCore.QSize(16777215, 20))
                self.label_15.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_15.setObjectName("label_15")
                self.gridLayout_7.addWidget(self.label_15, 0, 3, 1, 1)
                self.lineEdit_14 = QtWidgets.QLineEdit(self.widget_8)
                self.lineEdit_14.setStyleSheet("QLineEdit {\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit_14.setText("")
                self.lineEdit_14.setObjectName("lineEdit_14")
                self.gridLayout_7.addWidget(self.lineEdit_14, 1, 3, 1, 1)
                self.label_12 = QtWidgets.QLabel(self.widget_8)
                self.label_12.setMaximumSize(QtCore.QSize(16777215, 20))
                self.label_12.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_12.setObjectName("label_12")
                self.gridLayout_7.addWidget(self.label_12, 0, 0, 1, 1)
                self.lineEdit_11 = QtWidgets.QLineEdit(self.widget_8)
                self.lineEdit_11.setStyleSheet("QLineEdit {\n"
        "\n"
        "    padding-right: 20px; /* Adjust padding so text does not overlap the icon */\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit_11.setText("")
                self.lineEdit_11.setObjectName("lineEdit_11")
                self.gridLayout_7.addWidget(self.lineEdit_11, 1, 0, 1, 1)
                self.lineEdit_12 = QtWidgets.QLineEdit(self.widget_8)
                self.lineEdit_12.setStyleSheet("QLineEdit {\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit_12.setText("")
                self.lineEdit_12.setObjectName("lineEdit_12")
                self.gridLayout_7.addWidget(self.lineEdit_12, 1, 1, 1, 1)
                self.label_13 = QtWidgets.QLabel(self.widget_8)
                self.label_13.setMaximumSize(QtCore.QSize(16777215, 20))
                self.label_13.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_13.setObjectName("label_13")
                self.gridLayout_7.addWidget(self.label_13, 0, 1, 1, 1)
                self.label_14 = QtWidgets.QLabel(self.widget_8)
                self.label_14.setMaximumSize(QtCore.QSize(16777215, 20))
                self.label_14.setStyleSheet("color: black; \n"
        "border: none;\n"
        "background: transparent;\n"
        "text-align: left; /* Align the text inside the QPushButton to the left */\n"
        "padding-left: 0px;\n"
        "")
                self.label_14.setObjectName("label_14")
                self.gridLayout_7.addWidget(self.label_14, 0, 2, 1, 1)
                self.lineEdit_13 = QtWidgets.QLineEdit(self.widget_8)
                self.lineEdit_13.setStyleSheet("QLineEdit {\n"
        "    background-color: rgba(0, 0, 0, 0);\n"
        "    border-top: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-right: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-left: 1px solid rgba(105, 118, 132, 255);\n"
        "    border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
        "    color: rgba(255, 255, 255, 230);\n"
        "    padding-left: 2px;\n"
        "    border-radius: 3px; /* Adjust this value to change the roundness */\n"
        "}\n"
        "")
                self.lineEdit_13.setText("")
                self.lineEdit_13.setObjectName("lineEdit_13")
                self.gridLayout_7.addWidget(self.lineEdit_13, 1, 2, 1, 1)
                self.horizontalLayout_6.addWidget(self.widget_8)
                self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
                self.gridLayout_8.addWidget(self.scrollArea_3, 0, 0, 1, 1)
                self.widget_9 = QtWidgets.QWidget(self.page_5)
                self.widget_9.setObjectName("widget_9")
                self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.widget_9)
                self.horizontalLayout_7.setObjectName("horizontalLayout_7")
                self.pushButton_7 = QtWidgets.QPushButton(self.widget_9)
                self.pushButton_7.setObjectName("pushButton_7")
                self.horizontalLayout_7.addWidget(self.pushButton_7)
                self.pushButton_8 = QtWidgets.QPushButton(self.widget_9)
                self.pushButton_8.setObjectName("pushButton_8")
                self.pushButton_8.clicked.connect(lambda: self.saveWorkout(UserID))
                self.pushButton_6.clicked.connect(lambda: self.saveWorkout(UserID))
                self.pushButton_2.clicked.connect(lambda: self.saveWorkout(UserID))
                self.horizontalLayout_7.addWidget(self.pushButton_8)
                self.gridLayout_8.addWidget(self.widget_9, 1, 0, 1, 1)
                self.stackedWidget.addWidget(self.page_5)
                self.verticalLayout_6.addWidget(self.stackedWidget)
                self.MainStackedWidget.addWidget(self.page)
                self.horizontalLayout.addWidget(self.splitter)
                MainWindow.setCentralWidget(self.MainWindowWidget)
                self.menubar = QtWidgets.QMenuBar(MainWindow)
                self.menubar.setGeometry(QtCore.QRect(0, 0, 897, 22))
                self.menubar.setObjectName("menubar")
                MainWindow.setMenuBar(self.menubar)
                self.toolBar = QtWidgets.QToolBar(MainWindow)
                self.toolBar.setObjectName("toolBar")
                MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)


                self.retranslateUi(MainWindow)
                self.MainStackedWidget.setCurrentIndex(1)
                self.stackedWidget_6.setCurrentIndex(1)
                self.stackedWidget.setCurrentIndex(0)
                QtCore.QMetaObject.connectSlotsByName(MainWindow)



        def retranslateUi(self, MainWindow):
                _translate = QtCore.QCoreApplication.translate
                MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
                self.NameLabel.setText(_translate("MainWindow", "TextLabel"))
                self.SearchBar.setPlaceholderText(_translate("MainWindow", "MM/DD/YYYY"))
                self.GoalsButton.setText(_translate("MainWindow", "Goals"))
                self.EventsButton.setText(_translate("MainWindow", "Upcoming Events"))
                self.WorkoutsButton.setText(_translate("MainWindow", "Workouts"))
                self.StatsButton.setText(_translate("MainWindow", "Stats"))
                self.ProgressButton.setText(_translate("MainWindow", "Progress"))
                self.SettingsButton.setText(_translate("MainWindow", "Settings"))
                self.HelpButton.setText(_translate("MainWindow", "Help"))
                self.LogOutButton.setText(_translate("MainWindow", "Log Out"))
                self.DistanceLabel_5.setText(_translate("MainWindow", "Distance (km)"))
                self.DurationLabel_5.setText(_translate("MainWindow", "Duration"))
                self.GWorkoutsAmount_5.setText(_translate("MainWindow", "0"))
                self.GWorkoutsLabel_5.setText(_translate("MainWindow", "Gym Workouts"))
                self.RacesLabel_5.setText(_translate("MainWindow", "Races"))
                self.GymFilterButton_5.setText(_translate("MainWindow", "Gym"))
                self.RacesAmount_5.setText(_translate("MainWindow", "0"))
                self.TWorkoutsAmount_5.setText(_translate("MainWindow", "0"))
                self.AllFilterButton_5.setText(_translate("MainWindow", "All"))
                self.DistanceAmount_5.setText(_translate("MainWindow", "0.00"))
                self.TrainingFilterButton_5.setText(_translate("MainWindow", "Training"))
                self.DurationAmount_5.setText(_translate("MainWindow", "0:00.00"))
                self.ActivityLabel_5.setText(_translate("MainWindow", "Activity"))
                self.RaceFilterButton_5.setText(_translate("MainWindow", "Race"))
                self.TWorkoutsLabel_5.setText(_translate("MainWindow", "Track Workouts"))
                self.DateLabelDash_5.setText(_translate("MainWindow", "Date"))
                self.ActivityLabelDash_5.setText(_translate("MainWindow", "Activity"))
                self.DistancesLabelDash_5.setText(_translate("MainWindow", "Distances"))
                self.FocusLabelDash_5.setText(_translate("MainWindow", "Focus"))
                self.AddWorkoutButtonWidget_5.setText(_translate("MainWindow", "+"))
                self.WorkoutsAmountDefaultLabel_5.setText(_translate("MainWindow", "             You have no workouts for this month."))
                self.label_2.setText(_translate("MainWindow", "Workout Name"))
                self.lineEdit.setPlaceholderText(_translate("MainWindow", "MM/DD/YYYY"))
                self.label_3.setText(_translate("MainWindow", "Start Time"))
                self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "HH:MM AM/PM"))
                self.label_4.setText(_translate("MainWindow", "Date"))
                self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "MM/DD/YYYY"))
                self.label.setText(_translate("MainWindow", "<font color=\"black\">Activity <font color=\"red\">*</font>\n"
        ""))
                self.comboBox.setItemText(1, _translate("MainWindow", "Race"))
                self.comboBox.setItemText(2, _translate("MainWindow", "Training"))
                self.comboBox.setItemText(3, _translate("MainWindow", "Gym"))
                self.pushButton.setText(_translate("MainWindow", "Add another run"))
                self.pushButton_2.setText(_translate("MainWindow", "Save"))
                self.label_5.setText(_translate("MainWindow", "Enter Distance (m)"))
                self.label_6.setText(_translate("MainWindow", "Enter Time"))
                self.label_7.setText(_translate("MainWindow", "Enter Run(s)"))
                self.label_8.setText(_translate("MainWindow", "Enter Time(s)"))
                self.label_9.setText(_translate("MainWindow", "Enter Effort %"))
                self.label_10.setText(_translate("MainWindow", "Enter Rest"))
                self.label_11.setText(_translate("MainWindow", "Enter Focus"))
                self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "6x100m"))
                self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "70%"))
                self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "70%"))
                self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "e.g. Tempo"))
                self.pushButton_5.setText(_translate("MainWindow", "Add another run"))
                self.pushButton_6.setText(_translate("MainWindow", "Save"))
                self.label_15.setText(_translate("MainWindow", "Enter Reps"))
                self.lineEdit_14.setPlaceholderText(_translate("MainWindow", "12"))
                self.label_12.setText(_translate("MainWindow", "Enter Exercise"))
                self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "Bench Press"))
                self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "135lbs/60kg"))
                self.label_13.setText(_translate("MainWindow", "Enter Weight"))
                self.label_14.setText(_translate("MainWindow", "Enter Sets"))
                self.lineEdit_13.setPlaceholderText(_translate("MainWindow", "3"))
                self.pushButton_7.setText(_translate("MainWindow", "Add another exercise"))
                self.pushButton_8.setText(_translate("MainWindow", "Save"))
                self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))





                self.WorkoutsButton.clicked.connect(self.show_dashboard)
                self.pushButton_5.clicked.connect(self.addTraining)
                self.pushButton.clicked.connect(self.addRace)
                self.pushButton_7.clicked.connect(lambda: self.fetchWorkouts(1))

                self.pushButton_7.clicked.connect(self.addGym)

                self.MainWindow = MainWindow
                self.comboBox.currentIndexChanged.connect(self.on_combobox_changed)


                self.MainWindow = MainWindow

        def show_dashboard(self):
                from UneditedDashboard4 import Ui_MainWindow
                # Create a QMainWindow instance for the dashboard
                self.dashboardWindow = QtWidgets.QMainWindow()

                # Create an instance of Ui_MainWindow
                self.dashboardUI = Ui_MainWindow()

                # Set up the dashboard UI
                self.dashboardUI.setupUi(self.dashboardWindow)

                # Show the dashboard window
                self.dashboardWindow.show()

                # Close the current (login) form
                self.MainWindow.close()
                # Define the function to show the Password Recovery form


        def addTraining(self):
                row = self.gridLayout_6.rowCount()

                timeEdit1 = QLineEdit()
                self.gridLayout_6.addWidget(timeEdit1, row, 0)

                timeEdit2 = QLineEdit()
                self.gridLayout_6.addWidget(timeEdit2, row, 1)

                timeEdit3 = QLineEdit()
                self.gridLayout_6.addWidget(timeEdit3, row, 2)

                timeEdit4 = QLineEdit()
                self.gridLayout_6.addWidget(timeEdit4, row, 3)

                timeEdit5 = QLineEdit()
                self.gridLayout_6.addWidget(timeEdit5, row, 4)

        def addRace(self):
                row = self.gridLayout_4.rowCount()

                timeEdit1 = QLineEdit()
                self.gridLayout_4.addWidget(timeEdit1, row, 0)

                timeEdit2 = QLineEdit()
                self.gridLayout_4.addWidget(timeEdit2, row, 1)

        def addGym(self):
                row = self.gridLayout_7.rowCount()

                timeEdit1 = QLineEdit()
                self.gridLayout_7.addWidget(timeEdit1, row, 0)

                timeEdit2 = QLineEdit()
                self.gridLayout_7.addWidget(timeEdit2, row, 1)

                timeEdit3 = QLineEdit()
                self.gridLayout_7.addWidget(timeEdit3, row, 2)

                timeEdit4 = QLineEdit()
                self.gridLayout_7.addWidget(timeEdit4, row, 3)

        def collect_data_from_layout(self, grid_layout):
                data = []
                temp = []
                rows = grid_layout.rowCount()
                cols = grid_layout.columnCount()

                for row in range(rows):
                        for col in range(cols):
                                widget = grid_layout.itemAtPosition(row, col).widget()
                                if isinstance(widget, QtWidgets.QLineEdit):
                                        temp.append(widget.text())
                                if self.comboBox.currentText() == 'Training': # Assuming each pair of LineEdits corresponds to Distance and Time
                                        if len(temp) == 5:
                                                data.append(tuple(temp))
                                                temp = []
                                if self.comboBox.currentText() == 'Gym':
                                        if len(temp) == 4:
                                                data.append(tuple(temp))
                                                temp = []
                                if self.comboBox.currentText() == 'Race':
                                        if len(temp) == 2:
                                                data.append(tuple(temp))
                                                temp = []
                return data


        def saveWorkout(self, UserID):
                WorkoutName = self.lineEdit.text()
                WorkoutTime = self.lineEdit_2.text()
                WorkoutDate = self.lineEdit_3.text()
                host = "localhost"
                user = "root"
                password = ""
                database = "fittrackpro"
                connection = mysql.connector.connect(
                host=host,
                user=user,
                password=password,
                database=database
                )
                cursor = connection.cursor()
                WorkoutType = self.comboBox.currentText()

                try:
                        if WorkoutType == "Gym":
                                # Insert into GymSessions table
                                gym_session_query = "INSERT INTO GymSessions (UserID, WorkoutName, StartTime, Date) VALUES (%s, %s, %s, %s)"
                                cursor.execute(gym_session_query, (UserID, WorkoutName, WorkoutTime, WorkoutDate))

                                connection.commit()
                                last_session_id = cursor.lastrowid

                                # Collect gym exercise data
                                gym_exercise_info = self.collect_data_from_layout(self.gridLayout_7)
                                print(gym_exercise_info)

                                # Iterate over each exercise (assuming each exercise is a tuple of ExerciseName, Weight, Sets, Reps)
                                for exercise_info in gym_exercise_info:
                                        exercise_name = exercise_info[0]  # Adjust indices based on your layout
                                        weight = exercise_info[1]
                                        sets = exercise_info[2]
                                        reps = exercise_info[3]

                                        # Insert into Exercises table
                                        exercise_query = "INSERT INTO Exercises (SessionID, ExerciseName) VALUES (%s, %s)"
                                        cursor.execute(exercise_query, (last_session_id, exercise_name))
                                        connection.commit()
                                        last_exercise_id = cursor.lastrowid

                                        # Insert into ExerciseDetails table
                                        details_query = "INSERT INTO ExerciseDetails (ExerciseID, Weight, Sets, Reps) VALUES (%s, %s, %s, %s)"
                                        cursor.execute(details_query, (last_exercise_id, weight, sets, reps))
                                        connection.commit()
                        elif WorkoutType == "Race":
                                # Insert the race information and get RaceID
                                query1 = "INSERT INTO Races (UserID, RaceName, RaceDate, StartTime) VALUES (%s, %s, %s, %s)"
                                cursor.execute(query1, (UserID, WorkoutName, WorkoutDate, WorkoutTime))
                                connection.commit()
                                last_race_id = cursor.lastrowid

                                # Collect race distances and times
                                race_distances = self.collect_data_from_layout(self.gridLayout_4)

                                # Insert each distance-time pair with the RaceID
                                query2 = "INSERT INTO RaceDistances (RaceID, Distance, RaceTime) VALUES (%s, %s, %s)"
                                for distance, race_time in race_distances:
                                        cursor.execute(query2, (last_race_id, distance, race_time))
                                        connection.commit()
                                        
                        elif WorkoutType == "Training":
                        # Insert into Workouts table
                                query = "INSERT INTO Workouts (UserID, WorkoutName, StartTime, Date) VALUES (%s, %s, %s, %s)"
                                cursor.execute(query, (UserID, WorkoutName, WorkoutTime, WorkoutDate))
                                connection.commit()
                                last_workout_id = cursor.lastrowid

                                # Collect training data
                                training_data = self.collect_data_from_layout(self.gridLayout_6)

                                # Insert into DistanceDetails table
                                query = "INSERT INTO DistanceDetails (WorkoutID, Distance, Time, EffortPercentage, RestTime, Focus) VALUES (%s, %s, %s, %s, %s, %s)"
                                for item in training_data:
                                        if len(item) == 5:  # Check if the item has 5 elements
                                                cursor.execute(query, (last_workout_id,) + item)
                                                connection.commit()
                except Exception as e:
                        print(f"An error occurred: {e}")
                finally:
                        connection.commit()
                        connection.close()

        def print_widget_names(self, layout):
                for i in range(layout.count()):
                        widget = layout.itemAt(i).widget()
                        if widget is not None:
                                print(widget.objectName())

                # Call this function with your grid layout
                                        

                        

        def fetchWorkouts(self, UserID):
                data = {'Training': [], 'Race': [], 'Gym': []}
                try:
                        connection = mysql.connector.connect(
                        host="localhost",
                        user="root",
                        password="",
                        database="fittrackpro"
                        )
                        cursor = connection.cursor()

                        # Fetch and format training sessions
                        training_query = """
                        SELECT W.Date, 'Training' AS Activity, 
                        GROUP_CONCAT(DISTINCT
                                CASE 
                                WHEN DistanceCounts.Count > 1 THEN CONCAT(DistanceCounts.Count, 'x', DistanceCounts.Distance, 'm')
                                ELSE CONCAT(DistanceCounts.Distance, 'm')
                                END ORDER BY DistanceCounts.Distance SEPARATOR ', '
                        ) AS Distances, 
                        MAX(DD.Focus) AS Focus
                        FROM Workouts W
                        LEFT JOIN DistanceDetails DD ON W.WorkoutID = DD.WorkoutID
                        LEFT JOIN (
                        SELECT WorkoutID, Distance, COUNT(*) AS Count
                        FROM DistanceDetails
                        GROUP BY WorkoutID, Distance
                        ) AS DistanceCounts ON W.WorkoutID = DistanceCounts.WorkoutID
                        WHERE W.UserID = %s
                        GROUP BY W.WorkoutID
                        """
                        cursor.execute(training_query, (UserID,))
                        for row in cursor:
                                formatted_row = (row[0], row[1], row[2] if row[2] else "-", row[3])
                                data['Training'].append(formatted_row)


                        # Fetch races
                        race_query = "SELECT RaceDate AS Date, 'Race' AS Activity, '' AS Distances, '' AS Focus FROM Races WHERE UserID = %s"
                        cursor.execute(race_query, (UserID,))
                        for row in cursor:
                                formatted_row = (row[0], row[1], "-", "-")
                                data['Race'].append(formatted_row)

                        # Fetch gym sessions
                        gym_query = "SELECT Date, 'Gym' AS Activity, '' AS Distances, '' AS Focus FROM GymSessions WHERE UserID = %s"
                        cursor.execute(gym_query, (UserID,))
                        for row in cursor:
                                formatted_row = (row[0], row[1], "-", "-")
                                data['Gym'].append(formatted_row)

                except Exception as e:
                        print(f"An error occurred: {e}")
                finally:
                        if connection.is_connected():
                                cursor.close()
                                connection.close()
                print(data)

                return data





        

                




        def on_combobox_changed(self, index):
                # Change the current page of the stacked widget based on the combo box selection
                self.stackedWidget.setCurrentIndex(index)



if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = ui_AddWorkout()
        ui.setupUi(MainWindow, UserID=1)
        MainWindow.show()
        sys.exit(app.exec_())
if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())
if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        MainWindow = QtWidgets.QMainWindow()
        ui = Ui_MainWindow()
        ui.setupUi(MainWindow)
        MainWindow.show()
        sys.exit(app.exec_())