# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector
from PyQt5 import QtCore, QtGui, QtWidgets
import sys, res
import bcrypt
import webbrowser
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QHBoxLayout, QLabel, QLineEdit, QPushButton
from PyQt5.QtCore import Qt


class ClickableLabel(QLabel):
    clicked = QtCore.pyqtSignal()  # Signal to be emitted when the label is clicked

    def __init__(self, parent=None):
        super(ClickableLabel, self).__init__(parent)

    def mousePressEvent(self, event):
        if event.button() == Qt.LeftButton:
            self.clicked.emit()






class LoginForm(object):


        def open_url(self,url):
                webbrowser.open(url)



        def setupUi(self, Form):
                Form.setObjectName("Form")
                Form.resize(400, 550)
                Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
                Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
                self.widget = QtWidgets.QWidget(Form)
                self.widget.setGeometry(QtCore.QRect(30, 30, 370, 480))

                titleBarLayout = QHBoxLayout()

                # Minimize Button
                self.minimizeButton = QPushButton('-')
                self.minimizeButton.clicked.connect(lambda: Form.showMinimized())
                titleBarLayout.addWidget(self.minimizeButton)

                # Close Button
                self.closeButton = QPushButton('X')
                self.closeButton.clicked.connect(lambda: Form.close())
                titleBarLayout.addWidget(self.closeButton)

                # Main layout
                mainLayout = QVBoxLayout(Form)
                mainLayout.addLayout(titleBarLayout)
                mainLayout.addWidget(self.widget)  # Assuming 'self.widget' is your main content widget

                Form.setLayout(mainLayout)
                self.widget.setStyleSheet("QPushButton #pushButton{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop: 1 rgba(85, 98, 112,226));\n"
                "\n"
                "color:rgba(255, 255, 255, 210);\n"
                "border-radius:5px;\n"
                "}\n"
                "QPushButton #pushButton:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop: 1 rgba(105, 118, 132,226));\n"
                "}\n"
                "QPushButton #pushButton:pressed{\n"
                "padding-left:5px;\n"
                "padding-top:5px;\n"
                "background-color:rgba(105, 118, 132, 200);|\n"
                "}\n"
                "\n"
                "QPushButton #pushButton_3, #pushButton_4, #pushButton_6, #pushButton_5{\n"
                "\n"
                "background-color: rgba(0, 0, 0, 0);\n"
                "color:rgba(85, 98, 112, 255);\n"
                "}\n"
                "QPushButton #pushButton_6:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{ \n"
                "color:rgba(155, 168, 182, 220);\n"
                "}\n"
                "QPushButton #pushButton_6:pressed #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{ \n"
                "padding-left:5px;\n"
                "padding-top:5px;\n"
                "color:rgba(115, 128, 142, 255);\n"
                "}")
                self.widget.setObjectName("widget")
                self.label = QtWidgets.QLabel(self.widget)
                self.label.setGeometry(QtCore.QRect(30, 30, 300, 420))
                self.label.setStyleSheet("border-image: url(:/images/672226c7e2cfa265f5e75344074ad62c.jpg);\n"
                "border-radius: 20px;\n"
                "")
                self.label.setText("")
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.widget)
                self.label_2.setGeometry(QtCore.QRect(30, 30, 300, 420))
                self.label_2.setStyleSheet("background-color:glineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75)); \n"
                "border-radius:20px;")
                self.label_2.setText("")
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.widget)
                self.label_3.setGeometry(QtCore.QRect(40, 60, 280, 390))
                self.label_3.setStyleSheet("background-color:rgba(0,0,0,100);\n"
                "border-radius:15px;")
                self.label_3.setText("")
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.widget)
                self.label_4.setGeometry(QtCore.QRect(115, 95, 130, 40))
                font = QtGui.QFont()
                font.setPointSize(20)
                font.setBold(True)
                font.setWeight(75)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("color:rgba(255,255,255,210)")
                self.label_4.setObjectName("label_4")
                self.lineEdit = QtWidgets.QLineEdit(self.widget)
                self.lineEdit.setGeometry(QtCore.QRect(80, 165, 200, 40))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit.setFont(font)
                self.lineEdit.setStyleSheet("background-color:rgba(0, 0, 0, 0); \n"
                "border:none;\n"
                "border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
                "color:rgba(255, 255, 255, 230);\n"
                "padding-bottom:7px;")
                self.lineEdit.setObjectName("lineEdit")
                self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
                self.lineEdit_2.setGeometry(QtCore.QRect(80, 230, 200, 40))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_2.setFont(font)
                self.lineEdit_2.setStyleSheet("background-color:rgba(0, 0, 0, 0); \n"
                "border:none;\n"
                "border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
                "color:rgba(255, 255, 255, 230);\n"
                "padding-bottom:7px;")
                self.lineEdit_2.setObjectName("lineEdit_2")
                self.pushButton = QtWidgets.QPushButton(self.widget)
                self.pushButton.setGeometry(QtCore.QRect(80, 280, 200, 30))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton.setFont(font)
                self.pushButton.setObjectName("pushButton")
                self.pushButton.clicked.connect(self.handleLogin)

                self.pushButton_2 = QtWidgets.QPushButton(self.widget)
                self.pushButton_2.setGeometry(QtCore.QRect(80, 320, 200, 30))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_2.setFont(font)
                self.pushButton_2.setObjectName("pushButton_2")
                self.pushButton_2.clicked.connect(self.showSignUp)
                self.Form = Form
                self.label_5 = ClickableLabel(self.widget)
                self.label_5.setGeometry(QtCore.QRect(60, 370, 280, 21))
                self.label_5.setStyleSheet("color:rgba(255,255,255,140); font-weight: bold;")
                self.label_5.setObjectName("label_5")
                self.label_5.clicked.connect(self.showPasswordRecovery)
                self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
                self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 410, 131, 31))
                self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
                self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
                self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
                self.horizontalLayout.setObjectName("horizontalLayout")
                self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
                self.pushButton_5.setMaximumSize(QtCore.QSize(30, 30))
                font = QtGui.QFont()
                font.setFamily("Social Media Circled")
                font.setPointSize(15)
                self.pushButton_5.setFont(font)
                self.pushButton_5.setObjectName("pushButton_5")
                
                self.horizontalLayout.addWidget(self.pushButton_5)
                self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
                self.pushButton_6.setMaximumSize(QtCore.QSize(30, 30))
                
                font = QtGui.QFont()
                font.setFamily("Social Media Circled")
                font.setPointSize(15)
                self.pushButton_6.setFont(font)
                self.pushButton_6.setObjectName("pushButton_6")
                self.horizontalLayout.addWidget(self.pushButton_6)
                self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
                self.pushButton_4.setMaximumSize(QtCore.QSize(30, 30))
                font = QtGui.QFont()
                font.setFamily("Social Media Circled")
                font.setPointSize(15)
                self.pushButton_4.setFont(font)
                self.pushButton_4.setObjectName("pushButton_4")
                self.horizontalLayout.addWidget(self.pushButton_4)
                self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
                self.pushButton_3.setMaximumSize(QtCore.QSize(30, 30))
                font = QtGui.QFont()
                font.setFamily("Social Media Circled")
                font.setPointSize(15)
                self.pushButton_3.setFont(font)
                self.pushButton_3.setObjectName("pushButton_3")
                self.horizontalLayout.addWidget(self.pushButton_3)

                self.label.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(234,221,186,100)))
                self.label_3.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=0, yOffset=0, color=QtGui.QColor(105,118,132,100)))
                self.pushButton.setGraphicsEffect(QtWidgets.QGraphicsDropShadowEffect(blurRadius=25, xOffset=3, yOffset=3, color=QtGui.QColor(105,118,132,100)))

                self.pushButton_6.clicked.connect(lambda: self.open_url('https://twitter.com/JMeghoo'))
                self.pushButton_5.clicked.connect(lambda: self.open_url('https://www.facebook.com/IIAxzd/'))
                self.pushButton_3.clicked.connect(lambda: self.open_url('https://www.linkedin.com/in/jsmmeghoo-932b8019b/'))

                self.retranslateUi(Form)
                QtCore.QMetaObject.connectSlotsByName(Form)

        def validate_password(self,username,input_password):
                host = "localhost"
                user = "root"
                password = ""
                database = "fittrackpro"

                # Create a connection to the database
                connection = mysql.connector.connect(
                host=host,
                user=user,
                password=password,
                database=database
                )
                cursor = connection.cursor()
                cursor.execute("SELECT UserID, PasswordHash FROM user WHERE username = %s", (username,))
                result = cursor.fetchone()
                if result:
                        user_id, stored_hashed_password = result
                        input_password_encoded = input_password.encode("utf-8")
                        if bcrypt.checkpw(input_password_encoded, stored_hashed_password.encode("utf-8")):
                                return user_id
                        return -1
                return -2

        def handleLogin(self):
                username = self.lineEdit.text()
                input_password = self.lineEdit_2.text()
                if not username.strip() or not input_password.strip():
                        QtWidgets.QMessageBox.warning(self.widget, 'Error', 'One or more fields are empty')
                        return

                user_id = self.validate_password(username, input_password)
                if user_id == -1:
                        QtWidgets.QMessageBox.warning(self.widget, 'Error', 'Incorrect Password')
                elif user_id == -2:
                        QtWidgets.QMessageBox.warning(self.widget, 'Error', 'User not found')
                else:
                        self.showDashboard(user_id)
                        return
                
        # Define the function to show the Dashboard form
        def showDashboard(self, user_id):
                from FitTrackPro import Ui_MainWindow
                # Create a QMainWindow instance for the dashboard
                self.dashboardWindow = QtWidgets.QMainWindow()

                # Create an instance of Ui_MainWindow
                self.dashboardUI = Ui_MainWindow()

                # Set up the dashboard UI
                self.dashboardUI.setupUi(self.dashboardWindow, user_id)
                # Show the dashboard window
                self.dashboardWindow.show()

                # Close the current (login) form
                self.Form.close()
                # Define the function to show the Password Recovery form

        def showPasswordRecovery(self):
                from PasswordRecovery import Ui_Recovery        
                PasswordRecovery = QtWidgets.QWidget()

                # Create an instance of the Ui_LoginForm class
                ui = Ui_Recovery()

                # Set up the UI on the login_form widget
                ui.setupUi(PasswordRecovery)

                # Show the login form
                PasswordRecovery.show()
                self.Form.hide()

        # Define the function to show the Sign Up form
        def showSignUp(self):
                from register import UI_SignUp
                self.window = QtWidgets.QWidget()
                self.ui = UI_SignUp()
                self.ui.setupUi(self.window)
                self.window.show()
                self.Form.hide()

               


              

                


        def retranslateUi(self, Form):
                _translate = QtCore.QCoreApplication.translate
                Form.setWindowTitle(_translate("Form", "Form"))
                self.label_4.setText(_translate("Form", "LOGIN"))
                self.lineEdit.setPlaceholderText(_translate("Form", "Username"))
                self.lineEdit_2.setPlaceholderText(_translate("Form", "Password"))
                self.pushButton.setText(_translate("Form", "LOGIN"))
                self.pushButton_2.setText(_translate("Form", "SIGN UP"))
                self.label_5.setText(_translate("Form", "Forgot Username or Password?"))
                self.pushButton_5.setText(_translate("Form", "E"))
                self.pushButton_6.setText(_translate("Form", "D"))
                self.pushButton_4.setText(_translate("Form", "0"))
                self.pushButton_3.setText(_translate("Form", "C"))



if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = LoginForm()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())