# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PasswordRecovery.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import res, sys
import mysql.connector
import re
from PyQt5.QtWidgets import QApplication, QLabel, QMainWindow





class ClickableLabel(QLabel):
    def __init__(self, text):
        super().__init__(text)

    def mousePressEvent(self, event):
        # This method is called when the label is clicked.
        # You can put your custom code here.
        print("Label clicked!")



class Ui_Recovery(object):
        def setupUi(self, Form):
                Form.setObjectName("Form")
                Form.resize(450, 550)
                Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
                Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
                self.widget = QtWidgets.QWidget(Form)
                self.widget.setGeometry(QtCore.QRect(30, 30, 400, 480))
                self.widget.setStyleSheet("QPushButton #pushButton{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop: 1 rgba(85, 98, 112,226));\n"
                "\n"
                "color:rgba(255, 255, 255, 210);\n"
                "border-radius:5px;\n"
                "}\n"
                "QPushButton #pushButton:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop: 1 rgba(105, 118, 132,226));\n"
                "}\n"
                "QPushButton #pushButton:pressed{\n"
                "padding-left:5px;\n"
                "padding-top:5px;\n"
                "background-color:rgba(105, 118, 132, 200);|\n"
                "}\n"
                "\n"
                "QPushButton #pushButton_3, #pushButton_4, #pushButton_6, #pushButton_5{\n"
                "\n"
                "background-color: rgba(0, 0, 0, 0);\n"
                "color:rgba(85, 98, 112, 255);\n"
                "}\n"
                "QPushButton #pushButton_6:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{ \n"
                "color:rgba(155, 168, 182, 220);\n"
                "}\n"
                "QPushButton #pushButton_6:pressed #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{ \n"
                "padding-left:5px;\n"
                "padding-top:5px;\n"
                "color:rgba(115, 128, 142, 255);\n"
                "}")
                self.widget.setObjectName("widget")
                self.Form = Form
                self.label = QtWidgets.QLabel(self.widget)
                self.label.setGeometry(QtCore.QRect(30, 30, 300, 420))
                self.label.setStyleSheet("border-image: url(:/images/672226c7e2cfa265f5e75344074ad62c.jpg);\n"
                "border-radius: 20px;\n"
                "")
                self.label.setText("")
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.widget)
                self.label_2.setGeometry(QtCore.QRect(30, 30, 300, 420))
                self.label_2.setStyleSheet("background-color:glineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75)); \n"
                "border-radius:20px;")
                self.label_2.setText("")
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.widget)
                self.label_3.setGeometry(QtCore.QRect(40, 60, 280, 390))
                self.label_3.setStyleSheet("background-color:rgba(0,0,0,100);\n"
                "border-radius:15px;")
                self.label_3.setText("")
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.widget)
                self.label_4.setGeometry(QtCore.QRect(85, 100, 200, 40))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("color:rgba(255,255,255,210)")
                self.label_4.setObjectName("label_4")
                self.pushButton_2 = QtWidgets.QPushButton(self.widget)
                self.pushButton_2.setGeometry(QtCore.QRect(80, 280, 200, 30))
                self.pushButton_2.clicked.connect(self.handleRecovery)
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_2.setFont(font)
                self.pushButton_2.setObjectName("pushButton_2")
                self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
                self.lineEdit_4.setGeometry(QtCore.QRect(80, 220, 200, 31))
                font = QtGui.QFont()
                font.setPointSize(10)
                self.lineEdit_4.setFont(font)
                self.lineEdit_4.setStyleSheet("border-radius:5px;")
                self.lineEdit_4.setPlaceholderText("")
                self.lineEdit_4.setObjectName("lineEdit_4")
                self.label_5 = QtWidgets.QLabel(self.widget)
                self.label_5.setGeometry(QtCore.QRect(80, 150, 171, 41))
                self.label_5.setStyleSheet("color:rgba(255,255,255,210)")
                self.label_5.setWordWrap(True)
                self.label_5.setObjectName("label_5")
                self.label_6 = QtWidgets.QLabel(self.widget)
                self.label_6.setGeometry(QtCore.QRect(80, 200, 47, 14))
                self.label_6.setStyleSheet("color:rgba(255,255,255,210)")
                self.label_6.setObjectName("label_6")
                self.label_7 = QtWidgets.QLabel(self.widget)
                self.label_7.setGeometry(QtCore.QRect(80, 350, 171, 31))
                self.label_7.setStyleSheet("color:rgba(255,255,255,210)")
                self.label_7.setWordWrap(True)
                self.label_7.setObjectName("label_7")
                self.label_8 = ClickableLabel("Sign up.")  # Use the custom ClickableLabel
                self.label_8.setGeometry(QtCore.QRect(250, 350, 121, 31))
                self.label_8.setStyleSheet("color: blue; font-size: 12px;")  # Add font-size for better visibility
                self.label_8.setObjectName("label_8")
                self.label_8.setParent(self.widget)
                self.label_8.mousePressEvent = self.showSignUp



                # Connect the label's clicked signal to the ClickableLabel's slot (function)
                self.label_8.mousePressEvent = self.label_8.mousePressEvent

                self.retranslateUi(Form)
                QtCore.QMetaObject.connectSlotsByName(Form)

        def handleRecovery(self):
                email = self.lineEdit_4.text()
                if not email.strip():
                        return
                host = "localhost"
                user = "root"
                password = ""
                database = "fittrackpro"

                # Create a connection to the database
                connection = mysql.connector.connect(
                host=host,
                user=user,
                password=password,
                database=database
                )
                cursor = connection.cursor()
                cursor.execute("SELECT email FROM user WHERE email = %s", (email,))
                result = cursor.fetchone()
                if result and self.validate_email(email):
                        self.showPasswordReset(email)
                        return
                elif result and not self.validate_email(email):
                        return
                QtWidgets.QMessageBox.warning(self.widget, 'Error', 'Email not found')
                return  

        def validate_email(self,email):
                
                pattern = r'^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'

                # Use the re.match function to check if the email matches the pattern
                if re.match(pattern, email):
                        return True
                else:
                        return False

        def showSignUp(self):
                from register import UI_SignUp
                self.window = QtWidgets.QWidget()
                self.ui = UI_SignUp()
                self.ui.setupUi(self.window)
                self.window.show()

        def showPasswordReset(self,email=None):
                from PasswordReset import Ui_Reset
                self.window = QtWidgets.QWidget()
                self.ui = Ui_Reset()
                self.ui.setupUi(self.window, email)
                self.window.show()


        def retranslateUi(self, Form):
                _translate = QtCore.QCoreApplication.translate
                Form.setWindowTitle(_translate("Form", "Form"))
                self.label_4.setText(_translate("Form", "Password Recovery"))
                self.pushButton_2.setText(_translate("Form", "Continue"))
                self.label_5.setText(_translate("Form", "Enter your email"))
                self.label_6.setText(_translate("Form", "Email"))
                self.label_7.setText(_translate("Form", "Don\'t have an account?"))
                self.label_8.setText(_translate("Form", "Sign up."))



if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_Recovery()
        ui.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())