# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PasswordReset.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys, res
import mysql.connector
import bcrypt




class Ui_Reset(object):

        def setupUi(self, Form, email):
                self.Form = Form
                self.email = email
                Form.setObjectName("Form")
                Form.resize(450, 550)
                Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
                Form.setAttribute(QtCore.Qt.WA_TranslucentBackground)
                self.widget = QtWidgets.QWidget(Form)
                self.widget.setGeometry(QtCore.QRect(30, 30, 370, 480))
                self.widget.setStyleSheet("QPushButton #pushButton{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(20, 47, 78, 219), stop: 1 rgba(85, 98, 112,226));\n"
                "\n"
                "color:rgba(255, 255, 255, 210);\n"
                "border-radius:5px;\n"
                "}\n"
                "QPushButton #pushButton:hover{\n"
                "background-color: qlineargradient(spread:pad, x1:0, y1:0.505682, x2:1, y2:0.477, stop:0 rgba(40, 67, 98, 219), stop: 1 rgba(105, 118, 132,226));\n"
                "}\n"
                "QPushButton #pushButton:pressed{\n"
                "padding-left:5px;\n"
                "padding-top:5px;\n"
                "background-color:rgba(105, 118, 132, 200);|\n"
                "}\n"
                "\n"
                "QPushButton #pushButton_3, #pushButton_4, #pushButton_6, #pushButton_5{\n"
                "\n"
                "background-color: rgba(0, 0, 0, 0);\n"
                "color:rgba(85, 98, 112, 255);\n"
                "}\n"
                "QPushButton #pushButton_6:hover, #pushButton_3:hover, #pushButton_4:hover, #pushButton_5:hover{ \n"
                "color:rgba(155, 168, 182, 220);\n"
                "}\n"
                "QPushButton #pushButton_6:pressed #pushButton_3:pressed, #pushButton_4:pressed, #pushButton_5:pressed{ \n"
                "padding-left:5px;\n"
                "padding-top:5px;\n"
                "color:rgba(115, 128, 142, 255);\n"
                "}")
                self.widget.setObjectName("widget")
                self.label = QtWidgets.QLabel(self.widget)
                self.label.setGeometry(QtCore.QRect(30, 30, 300, 420))
                self.label.setStyleSheet("border-image: url(:/images/672226c7e2cfa265f5e75344074ad62c.jpg);\n"
                "border-radius: 20px;\n"
                "")
                self.label.setText("")
                self.label.setObjectName("label")
                self.label_2 = QtWidgets.QLabel(self.widget)
                self.label_2.setGeometry(QtCore.QRect(30, 30, 300, 420))
                self.label_2.setStyleSheet("background-color:glineargradient(spread:pad, x1:0, y1:0, x2:0, y2:0.715909, stop:0 rgba(0, 0, 0, 9), stop:0.375 rgba(0, 0, 0, 50), stop:0.835227 rgba(0, 0, 0, 75)); \n"
                "border-radius:20px;")
                self.label_2.setText("")
                self.label_2.setObjectName("label_2")
                self.label_3 = QtWidgets.QLabel(self.widget)
                self.label_3.setGeometry(QtCore.QRect(40, 60, 280, 390))
                self.label_3.setStyleSheet("background-color:rgba(0,0,0,100);\n"
                "border-radius:15px;")
                self.label_3.setText("")
                self.label_3.setObjectName("label_3")
                self.label_4 = QtWidgets.QLabel(self.widget)
                self.label_4.setGeometry(QtCore.QRect(100, 100, 190, 40))
                font = QtGui.QFont()
                font.setPointSize(10)
                font.setBold(True)
                font.setWeight(75)
                self.label_4.setFont(font)
                self.label_4.setStyleSheet("color:rgba(255,255,255,210)")
                self.label_4.setObjectName("label_4")
                self.pushButton_2 = QtWidgets.QPushButton(self.widget)
                self.pushButton_2.setGeometry(QtCore.QRect(80, 300, 200, 30))
                font = QtGui.QFont()
                font.setPointSize(12)
                font.setBold(True)
                font.setWeight(75)
                self.pushButton_2.setFont(font)
                self.pushButton_2.setObjectName("pushButton_2")
                self.pushButton_2.clicked.connect(self.resetPassword)
                self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
                self.lineEdit_4.setGeometry(QtCore.QRect(80, 200, 200, 31))
                font = QtGui.QFont()
                font.setPointSize(8)
                self.lineEdit_4.setFont(font)
                self.lineEdit_4.setStyleSheet("border-radius:5px;")
                self.lineEdit_4.setObjectName("lineEdit_4")
                self.label_5 = QtWidgets.QLabel(self.widget)
                self.label_5.setGeometry(QtCore.QRect(100, 150, 181, 31))
                self.label_5.setStyleSheet("color:rgba(255,255,255,210)")
                self.label_5.setWordWrap(True)
                self.label_5.setObjectName("label_5")
                self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
                self.lineEdit_5.setGeometry(QtCore.QRect(80, 240, 200, 31))
                font = QtGui.QFont()
                font.setPointSize(8)
                self.lineEdit_5.setFont(font)
                self.lineEdit_5.setStyleSheet("border-radius:5px;")
                self.lineEdit_5.setObjectName("lineEdit_5")

                self.retranslateUi(Form)
                QtCore.QMetaObject.connectSlotsByName(Form)


        def resetPassword(self):
                input_password = self.lineEdit_4.text()
                confirm_password = self.lineEdit_5.text()
                if not confirm_password.strip() or not input_password.strip():
                        QtWidgets.QMessageBox.warning(self.widget, 'Error', 'One or more field are empty')
                        return          

                if input_password != confirm_password:
                        QtWidgets.QMessageBox.warning(self.widget, 'Error', 'Passwords do not match')
                        return
                else:
                        hashed_password = bcrypt.hashpw(input_password.encode('utf-8'), bcrypt.gensalt())
                conn = mysql.connector.connect(
                        host="localhost",
                        user="root",
                        password="",
                        database = "fittrackpro"
                        )
                cursor = conn.cursor()
                cursor.execute("UPDATE User SET PasswordHash = %s WHERE email = %s", (hashed_password, self.email))
                conn.commit()
                conn.close()
                QtWidgets.QMessageBox.information(self.widget, 'Success', 'Password Reset')
                self.showLogin()
                
        def showLogin(self):
                from loginUI import LoginForm
                login_form = QtWidgets.QWidget()

                # Create an instance of the Ui_LoginForm class
                ui = LoginForm()

                # Set up the UI on the login_form widget
                ui.setupUi(login_form)

                # Show the login form
                self.Form.hide()

                login_form.show()



        def retranslateUi(self, Form):
                _translate = QtCore.QCoreApplication.translate
                Form.setWindowTitle(_translate("Form", "Form"))
                self.label_4.setText(_translate("Form", "Reset password"))
                self.pushButton_2.setText(_translate("Form", "Reset Password"))
                self.lineEdit_4.setPlaceholderText(_translate("Form", "Password"))
                self.label_5.setText(_translate("Form", "Enter a new password"))
                self.lineEdit_5.setPlaceholderText(_translate("Form", "Confirm Password"))

if __name__ == "__main__":
        app = QtWidgets.QApplication(sys.argv)
        Form = QtWidgets.QWidget()
        ui = Ui_Reset()
        ui.setupUi(Form,email=None)
        Form.show()
        sys.exit(app.exec_())